export const COPY = {
  hero: {
    preTitle: "Invitación especial",
    title: "Sandra | Mis 60 años",
    subtitle: "Un brindis por las seis décadas de una vida extraordinaria.",
  },
  countdown: {
    label: "Cuenta regresiva",
    days: "Días",
    hours: "Hs",
    minutes: "Min",
    seconds: "Seg",
    expired: "¡El gran día llegó!",
  },
  dateTime: {
    label: "Fecha y hora",
    date: "sábado 30 de mayo",
    year: "2026",
    time: "21:30 HS",
  },
  venue: {
    label: "Lugar",
    howToArrive: "Cómo llegar",
  },
  dressCode: {
    label: "Dress Code",
    description: "Elegante Sport",
  },
  spotify: {
    label: "Música",
    sectionTitle: "Dedicale una canción a {name}",
    title: "Sumá tu canción",
    subtitle:
      "Elegí una canción que te haga acordar a ella o que quieras que suene en su fiesta. ¡Podés dejarle un mensaje también!",
    searchPlaceholder: "Buscar canción o artista...",
    contributorPlaceholder: "Tu nombre",
    messagePlaceholder: "Dejale un mensaje a {name} sobre esta canción...",
    submitButton: "Sumar a la playlist",
    successMessage: "¡Tu canción fue agregada a la playlist!",
    contributedTitle: "Canciones dedicadas",
    emptyState: "Sé el primero en dedicar una canción.",
  },
  timeline: {
    label: "60 años en imágenes",
  },
  familyMessage: {
    label: "Un mensaje de la familia",
    message:
      "Queremos compartir este momento tan especial con todos los que son parte de la vida de {name}. ¡Los esperamos para festejar juntos!",
  },
  photoUpload: {
    label: "Galería colaborativa",
    title: "Compartí tus fotos con {name}",
    subtitle: "Subí fotos de momentos juntos para armar un álbum sorpresa.",
    uploadButton: "Subir foto",
    nameLabel: "Tu nombre",
    successMessage: "¡Foto subida! Será revisada antes de publicarse.",
  },
  gallery: {
    label: "Galería",
    title: "Momentos especiales",
    emptyState: "Las fotos aparecerán aquí una vez aprobadas.",
  },
  rsvp: {
    label: "Confirmación",
    title: "¿Vas a venir?",
    subtitle: "Confirmá tu asistencia antes del 25 de mayo.",
    attendingLabel: "¡Sí, voy!",
    notAttendingLabel: "No puedo ir",
    nameLabel: "Nombre completo",
    companionsLabel: "¿Venís con un acompañante?",
    dietaryLabel: "¿Alguna restricción alimentaria?",
    dietaryPlaceholder: "Celíaco, vegetariano, etc.",
    submitButton: "Responder invitación",
    successTitle: "¡Confirmado!",
    successMessage: "Te esperamos el 30 de mayo. ¡Va a ser una gran noche!",
    declineMessage: "¡Qué lástima! Te vamos a extrañar.",
    whatsappButton: "Confirmar por WhatsApp",
  },
  footer: {
    madeWith: "Hecho con",
    forCelebrant: "para {name}",
    addToCalendar: "Agregar al calendario",
  },
  admin: {
    title: "Panel de administración",
    songs: "Canciones",
    photos: "Fotos",
    rsvps: "Confirmaciones",
    approve: "Aprobar",
    reject: "Rechazar",
    pending: "Pendiente",
    approved: "Aprobada",
    rejected: "Rechazada",
    delete: "Eliminar",
  },
} as const;
